/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package unread_email_count;

/**
 *
 * @author MA
 */
public class BrigdeFrame extends javax.swing.JFrame {

    /**
     * Creates new form BrigdeFrame
     */
    public  String jhost_value = "localhost" ;  
    public  String jport_value = "8080"; 
    public static BrigdeFrame SingleObject = null;
    
    private BrigdeFrame() {
        initComponents();
    }
    
    public static BrigdeFrame GetInstance(){
        if(SingleObject == null)
            SingleObject = new BrigdeFrame();
        return SingleObject;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Login_jLabel = new javax.swing.JLabel();
        Login_jTextField = new javax.swing.JTextField();
        Password_jTextField = new javax.swing.JPasswordField();
        Password_jLabel = new javax.swing.JLabel();
        GetCount_jButton = new javax.swing.JButton();
        Output_jTextField = new javax.swing.JTextField();
        Settings_jToolBar = new javax.swing.JToolBar();
        OpenSettings_jButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Unread email count");

        Login_jLabel.setText("Login");

        Login_jTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Login_jTextFieldActionPerformed(evt);
            }
        });

        Password_jTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Password_jTextFieldActionPerformed(evt);
            }
        });

        Password_jLabel.setText("Password");

        GetCount_jButton.setText("Get Count");
        GetCount_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GetCount_jButtonActionPerformed(evt);
            }
        });

        Output_jTextField.setEnabled(false);
        Output_jTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Output_jTextFieldActionPerformed(evt);
            }
        });

        Settings_jToolBar.setBackground(new java.awt.Color(255, 255, 255));
        Settings_jToolBar.setFloatable(false);
        Settings_jToolBar.setRollover(true);

        OpenSettings_jButton.setBackground(new java.awt.Color(255, 255, 255));
        OpenSettings_jButton.setText("Settings");
        OpenSettings_jButton.setFocusable(false);
        OpenSettings_jButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        OpenSettings_jButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        OpenSettings_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpenSettings_jButtonActionPerformed(evt);
            }
        });
        Settings_jToolBar.add(OpenSettings_jButton);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Settings_jToolBar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(Login_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(Password_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Login_jTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                            .addComponent(Password_jTextField)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(GetCount_jButton, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(Output_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Settings_jToolBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Login_jLabel)
                    .addComponent(Login_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Password_jLabel)
                    .addComponent(Password_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GetCount_jButton)
                    .addComponent(Output_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(93, 93, 93))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Login_jTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Login_jTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Login_jTextFieldActionPerformed

    private void Password_jTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Password_jTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Password_jTextFieldActionPerformed

    private void GetCount_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GetCount_jButtonActionPerformed
        // TODO add your handling code here:
        Unread_email_count http = new Unread_email_count();
        try{
            //add validations for textInputs
            String passText = new String(Password_jTextField.getPassword());
            String result = http.sendGet(Login_jTextField.getText(), passText, jhost_value, jport_value);
            Output_jTextField.setText(result);}
        catch(Exception e){
            //add error message for retyping
            return;
        }
    }//GEN-LAST:event_GetCount_jButtonActionPerformed

    private void Output_jTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Output_jTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Output_jTextFieldActionPerformed

    private void OpenSettings_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpenSettings_jButtonActionPerformed
        // TODO add your handling code here:
        Settings window = new Settings();
        this.disable();
        window.setVisible(true);
    }//GEN-LAST:event_OpenSettings_jButtonActionPerformed
    public void SetEnable(){
        this.enable();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BrigdeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BrigdeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BrigdeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BrigdeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                 //new BrigdeFrame().setVisible(true);
                BrigdeFrame obj = BrigdeFrame.GetInstance();
                obj.setVisible(true);
            }
        });
    }
    public  void set_settings(String host, String port)
    {
        jhost_value = host;
        jport_value = port;
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GetCount_jButton;
    private javax.swing.JLabel Login_jLabel;
    private javax.swing.JTextField Login_jTextField;
    private javax.swing.JButton OpenSettings_jButton;
    private javax.swing.JTextField Output_jTextField;
    private javax.swing.JLabel Password_jLabel;
    private javax.swing.JPasswordField Password_jTextField;
    private javax.swing.JToolBar Settings_jToolBar;
    // End of variables declaration//GEN-END:variables
}
