/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package unread_email_count;

/**
 *
 * @author MA
 */
public class Settings extends javax.swing.JFrame {

    /**
     * Creates new form Settings
     */
    public Settings() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HostName_JTextField = new javax.swing.JTextField();
        PortNumber_JTextField = new javax.swing.JTextField();
        HostName_jLabel = new javax.swing.JLabel();
        PortNumber_jLabel = new javax.swing.JLabel();
        SetSettings_jButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Settings");

        HostName_JTextField.setText("localhost");
        HostName_JTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HostName_JTextFieldActionPerformed(evt);
            }
        });

        PortNumber_JTextField.setText("8080");
        PortNumber_JTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PortNumber_JTextFieldActionPerformed(evt);
            }
        });

        HostName_jLabel.setText("host");

        PortNumber_jLabel.setText("port");

        SetSettings_jButton.setText("Ok");
        SetSettings_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SetSettings_jButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(HostName_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PortNumber_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(HostName_JTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                    .addComponent(PortNumber_JTextField))
                .addContainerGap(116, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SetSettings_jButton)
                .addGap(44, 44, 44))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HostName_jLabel)
                    .addComponent(HostName_JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PortNumber_JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PortNumber_jLabel))
                .addGap(45, 45, 45)
                .addComponent(SetSettings_jButton)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleName("Settings");
        getAccessibleContext().setAccessibleParent(this);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HostName_JTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HostName_JTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HostName_JTextFieldActionPerformed

    private void PortNumber_JTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PortNumber_JTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PortNumber_JTextFieldActionPerformed

    private void SetSettings_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SetSettings_jButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        dispose();
        BrigdeFrame obj = BrigdeFrame.GetInstance();
        obj.SetEnable();
        obj.set_settings(HostName_JTextField.getText(),PortNumber_JTextField.getText());
    }//GEN-LAST:event_SetSettings_jButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField HostName_JTextField;
    private javax.swing.JLabel HostName_jLabel;
    private javax.swing.JTextField PortNumber_JTextField;
    private javax.swing.JLabel PortNumber_jLabel;
    private javax.swing.JButton SetSettings_jButton;
    // End of variables declaration//GEN-END:variables
}
